name: Build and GHPages Deploy

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '22.x'
      - run: npm install
      - run: npm run build
      - name: GitHub Pages Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
